id: I81922C3B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T00:07:05+00:00'
last_modified: '2022-06-08T16:31:37.028434+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29195
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ།（བཀྲས་ལྷུན་པར་རྙིང་། དྷ་སར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D041:
      image_group_id: I5152
      title: ''
      total_pages: 928
      order: 1
      base_file: D041.txt
    7AB7:
      image_group_id: I5153
      title: ''
      total_pages: 974
      order: 2
      base_file: 7AB7.txt
    2E72:
      image_group_id: I5154
      title: ''
      total_pages: 882
      order: 3
      base_file: 2E72.txt
    59BE:
      image_group_id: I5155
      title: ''
      total_pages: 918
      order: 4
      base_file: 59BE.txt
    '7232':
      image_group_id: I5156
      title: ''
      total_pages: 872
      order: 5
      base_file: 7232.txt
    2C36:
      image_group_id: I5157
      title: ''
      total_pages: 952
      order: 6
      base_file: 2C36.txt
    '3741':
      image_group_id: I5158
      title: ''
      total_pages: 962
      order: 7
      base_file: 3741.txt
    '6491':
      image_group_id: I5159
      title: ''
      total_pages: 918
      order: 8
      base_file: 6491.txt
    A346:
      image_group_id: I5160
      title: ''
      total_pages: 836
      order: 9
      base_file: A346.txt
    CCCC:
      image_group_id: I5161
      title: ''
      total_pages: 934
      order: 10
      base_file: CCCC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
