id: I81922C3B
legacy_id: P010652
ocr_import_info:
  bdrc_scan_id: W29195
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T23:58:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T09:58:40.152666+00:00'
last_modified: 2022-09-02 18:08:57.717881
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W29195
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW29195
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ།（བཀྲས་ལྷུན་པར་རྙིང་། དྷ་སར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.6250193423791436
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I5159:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5159
      total_pages: 918
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I5159.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6109735707026759
    legacy_id: v008
  I5158:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5158
      total_pages: 962
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I5158.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6264097939716448
    legacy_id: v007
  I5154:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5154
      total_pages: 882
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I5154.txt
    statistics:
      ocr_word_median_confidence_index: 0.6800000071525574
      ocr_word_mean_confidence_index: 0.6400448587308247
    legacy_id: v003
  I5152:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5152
      total_pages: 928
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5152.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5786663556664876
    legacy_id: v001
  I5157:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5157
      total_pages: 952
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I5157.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6233633451532575
    legacy_id: v006
  I5161:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5161
      total_pages: 934
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I5161.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6505613666843054
    legacy_id: v010
  I5156:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5156
      total_pages: 872
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I5156.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6180408098672788
    legacy_id: v005
  I5153:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5153
      total_pages: 974
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I5153.txt
    statistics:
      ocr_word_median_confidence_index: 0.6399999856948853
      ocr_word_mean_confidence_index: 0.6042969446612528
    legacy_id: v002
  I5155:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5155
      total_pages: 918
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I5155.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6396390864105859
    legacy_id: v004
  I5160:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5160
      total_pages: 836
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I5160.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6638296831626977
    legacy_id: v009
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
